services:
  - type: web
    name: truecarbon-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn app.main:app --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CORS_ORIGINS
        value: https://yourdomain.com
databases:
  - name: truecarbon-postgres
    databaseName: truecarbon
    user: truecarbon_user
    region: us-east
